version: '2'
services:
        poc-matricula:
                build: ../poc-matricula
                ports:
                        - "1000:8080"
                volumes:
                        - ../poc-matricula:/code
        db:
                build: ../poc-db
                ports:
                        - "3306:3306"

